### ISSUE TITLE
What does PAW stand for?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/paw#3]
Couldn’t find it anywhere :)

**Comment by ronaldtse** [comment]
Sorry... the current best answer is "Portable Archive of Web", where the character pair "WA" comes from "WARC" (Web ARChive format) standardized by ISO TC 46 / SC 10.

**Comment by strogonoff** [comment]
Neat! Apparently,

> WARC is now recognised by most national library systems as the standard to follow for web archival.

Seems like widespread browser support can be expected to come

**Comment by strogonoff** [comment]
Ahh but PAW is going to be different isn’t it

**Comment by ronaldtse** [comment]
I'm not sure if WARC will be implemented by browsers as WARC is a very specific format for web archival and have a number of quirks, such as not including compression, using a single text file to store all content, and mixing metadata with data. PAW could be a lightweight WARC (feature subset) with some additional features for portability and distribution (e.g., security).

**Comment by strogonoff** [comment]
Understood, more like MAFF, and with plugin support for interoperability (though if the standard works well enough one could hope for native implementation 🤞)

**Comment by ronaldtse** [comment]
We can indeed consider PAW a successor to (and a combination of the best parts of) MAFF and WARC.
